version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'password@123'
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql
    container_name: mssql

    restart: always

volumes:
  sqlvolume:
